### ISSUE TITLE
ind1 and ind2 variables not working

### ISSUE THREAD

**Issue by patrickshas** [earthinversion/geophysical-cross-correlation#1]
Hello 
In you towards data science instructional I get stuck here:

Compute the cross-correlation in time-domain
d1, d2 = timeSeriesDf[time_series[ind1]], timeSeriesDf[time_series[ind2]]

I believe ind1 and ind2 are not defined.

Could you please kindly give me some insight?

**Comment by earthinversion** [comment]
In this example, `timeSeriesDf[time_series[ind1]]`, and `timeSeriesDf[time_series[ind2]]` are the two pandas Series object as required by the `crosscorr` function. 

```
crosscorr(datax, datay, lag=0) where
datax, datay : pandas.Series objects of equal length
```

I read the time series from the Pandas DataFrame `timeSeriesDf`, for the specified columns `time_series[ind1]` and `time_series[ind2]`, where `time_series` is a list with two elements. `ind1` or `ind2` are indices of two elements in the list `time_series`, for e.g., `ind1=0` and `ind2=1`.

Alternatively, one can directly create Pandas Series object by using pd.Series().

**Comment by patrickshas** [comment]
Thanks for the clarification. This is the error I get:

    d1, d2 = timeSeriesDf[time_series[ind1]], timeSeriesDf[time_series[ind2]]
NameError: name 'ind1' is not defined

Am I missing a library?
Best

**Comment by patrickshas** [comment]
Just figured it out:

This works:

d1, d2 = timeSeriesDf[time_series[0]], timeSeriesDf[time_series[1]]
